name: Build Mod Cam Xa

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy Code Về
        uses: actions/checkout@v4

      - name: Cài đặt môi trường Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cài NDK và Ép Gradle nhận diện
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;24.0.7856742"
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ndk.dir=$ANDROID_HOME/ndk/24.0.7856742" >> local.properties

      - name: Cấp quyền chạy cho Gradle
        run: chmod +x ./gradlew

      - name: Tiến hành Build Mod
        run: ./gradlew assembleRelease
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/24.0.7856742

      - name: Lấy File .SO và APK
        uses: actions/upload-artifact@v4
        with:
          name: Thu-Vien-Mod-ChanelTeam
          path: app/build/outputs/
