name: Build Mod Cam Xa

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy Code Về
        uses: actions/checkout@v4

      - name: Cài đặt môi trường Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Chấp nhận điều khoản SDK để tải NDK
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Cấp quyền chạy cho Gradle
        run: chmod +x ./gradlew

      - name: Tiến hành Build Mod
        run: ./gradlew assembleRelease

      - name: Lấy File .SO và APK
        uses: actions/upload-artifact@v4
        with:
          name: Thu-Vien-Mod-ChanelTeam
          path: app/build/outputs/
